FROM golang:1.17-alpine
WORKDIR /app

RUN apk add curl && \
    curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY . .

ENV PORT 80
CMD air